analyzer:

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    - cancel_subscriptions
    - annotate_overrides
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
#    - always_specify_types
    - avoid_renaming_method_parameters
    - curly_braces_in_flow_control_structures
    - only_throw_errors
    - prefer_iterable_whereType
    - prefer_typing_uninitialized_variables
    - unnecessary_overrides
